name: Deploy Node.js Services to Azure VM

on:
  push:
    branches:
      - main
    paths:
      - "backend.js"
      - "worker.js"
      - "package.json"
      - "package-lock.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history so diffs work reliably

      - name: Detect changed files
        id: changes
        run: |
          echo "CHANGED_BACKEND=false" >> $GITHUB_ENV
          echo "CHANGED_WORKER=false" >> $GITHUB_ENV

          # ensure the ref is fetched (checkout --fetch-depth=0 above should be enough)
          git fetch --no-tags --prune origin ${{ github.ref }} || true

          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            # First push for this ref — list files touched in the pushed commit(s)
            CHANGED_FILES=$(git show --name-only --pretty="" "$AFTER" | sed '/^$/d' | sort -u)
          else
            CHANGED_FILES=$(git diff --name-only "$BEFORE" "$AFTER" | sed '/^$/d' | sort -u)
          fi

          echo "Changed files: $CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -q "backend.js"; then
            echo "CHANGED_BACKEND=true" >> $GITHUB_ENV
          fi

          if echo "$CHANGED_FILES" | grep -q "worker.js"; then
            echo "CHANGED_WORKER=true" >> $GITHUB_ENV
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script_stop: true
          script: |
            cd ~/ttsbackend
            git reset --hard
            git pull origin main
            npm install --production

            if [ "${CHANGED_BACKEND}" = "true" ]; then
              echo "Restarting backend.js..."
              pm2 restart backend || pm2 start backend.js --name backend
            fi

            if [ "${CHANGED_WORKER}" = "true" ]; then
              echo "Restarting worker.js..."
              pm2 restart worker || pm2 start worker.js --name worker
            fi
